services:
  postgres:
    image: postgres:16
    container_name: yk-apparels-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: yk_apparels
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - yk_apparels_postgres_data:/var/lib/postgresql/data

volumes:
  yk_apparels_postgres_data:
